// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const Verifier = artifacts.require('Verifier');
const Proof = require('../../zokrates/code/square/proof.json');

contract('Verifier', accounts => {

    const owner = accounts[0];

    // Test verification with correct proof
    // - use the contents from proof.json generated from zokrates steps
    describe('Test verification', function () {
        before(async function () {
            this.contract = await Verifier.new({ from: owner });
        })

        it('Verification with correct proof', async function () {
            let result = await this.contract.verifyTx(Proof.proof, Proof.inputs);
            assert.equal(result, true, "Verification with correct proof failed");
        })

        it('Verification with incorrect proof', async function () {
            let result = await this.contract.verifyTx(Proof.proof, [10, 1]);
            assert.equal(result, false, "Verification with incorrect proof failed");
        })
    });
})